function on_input(self, action_id, action)
	if action.pressed and action_id == hash("esc") then
		msg.post("controller#controller", "show_start_menu")
	end
end

function final(self)
	msg.post(".", "release_input_focus")
end

function on_message(self, message_id, message, sender)
	if message_id == hash("show") then
		msg.post(".", "enable")
		msg.post(".", "acquire_input_focus")
	elseif message_id == hash("hide") then
		msg.post(".", "disable")
		msg.post(".", "release_input_focus")
	end
end