local monarch = require "monarch.monarch"

function init(self)
    msg.post(".", "acquire_input_focus")
end

function final(self)
end

function update(self, dt)
end

function on_message(self, message_id, message, sender)
end

function on_input(self, action_id, action)
    if action.pressed and action_id == hash("key_n") then
        monarch.show("new_game_menu")
    end
end

function on_reload(self)
end
